@startuml
'https://plantuml.com/class-diagram

skinparam monochrome true
skinparam shadowing false

title 5.1.15 As an Admin, I want to list/search staff profiles, so that I can see the details, edit, and remove staff profiles.

class Admin{

}

class User{
    +ID: long
    +Username: String
    +Role: String
    +Email: String
}
class Slots{
    +Date: Date
    +StartingHour: Date
    +EndHour: Date
}

class Staff{
    +FirstName: String
    +LastName: String
    +FullName: String
    +LicenseNumber(ID): long
    +ContactInformation(ID-FK):long
    +PhoneNumber: int
    +AvailabilitySlots: Slots

}

class ContactInformation{
    +ID:long
    +Email: String
    +PhoneNumber: int
}
class SessionManager {
    +CreateSession(SessionToken token, Admin admin): Session
    +InvalidateSession(): void
}

class Session {
    +SessionID: string
    +Admin: Admin
    +CreatedAt: DateTime
    +ExpiresAt: DateTime
}
class IAMService {
    +Authenticate(IAMCredentials credentials): SessionToken
}


class SessionToken {
    +Token: string
    +Expiration: DateTime
    +IsValid(): bool
}

class StaffController{
    +createStaff(Staff staff)
}

class StaffService {
    +createStaff(Staff staff): Staff
}
class StaffRepository {
    +createStaff(Staff staff)
}
Slots-->Staff : uses
ContactInformation-->Staff :has
Admin-|>User
Admin --> SessionManager : uses
IAMService --> SessionToken : returns
SessionManager --> Session : creates
Admin --> IAMService : authenticates with
Admin --> StaffController : inserts data into
StaffController-->StaffService: create new staff
Staff-->StaffController:uses
StaffService-->StaffRepository: creates new staff
SessionToken --> Session : verifies
@enduml