@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title 5.1.14 As an Admin, I want to deactivate a staff profile, so that I can remove them from the hospital’s active roster without losing their historical data.


autonumber
actor "Admin" as ADMIN

participant "<<System>> \nSystem" as System

    ADMIN -> System : selects to deactivate a staff profile
    activate System

    System --> ADMIN : shows profile list
    deactivate System

    ADMIN -> System : selects a profile
    activate System


    System --> ADMIN : message success
    deactivate System    

@enduml
