@startuml
'https://plantuml.com/class-diagram

skinparam monochrome true
skinparam shadowing false

title Class Diagram - As an Admin, I want to create a new staff profile, so that I can add them to the hospital’s roster.

class Admin{

}

class User{
    +ID: long
    +Username: String
    +Role: String
    +Email: String
}
class Slots{
    +Date: Date
    +StartingHour: Date
    +EndHour: Date
}

class Staff{
    +FirstName: String
    +LastName: String
    +FullName: String
    +LicenseNumber(ID): long
    +ContactInformation(ID-FK):long
    +PhoneNumber: int
    +AvailabilitySlots: Slots

}

class ContactInformation{
    +ID:long
    +Email: String
    +PhoneNumber: int
}
class SessionManager {
    +CreateSession(SessionToken token, Admin admin): Session
    +InvalidateSession(): void
}

class Session {
    +SessionID: string
    +Admin: Admin
    +CreatedAt: DateTime
    +ExpiresAt: DateTime
}
class IAMService {
    +Authenticate(IAMCredentials credentials): SessionToken
}



class SessionToken {
    +Token: string
    +Expiration: DateTime
    +IsValid(): bool
}

class StaffController{
    +FetchStaffbyID(long id)
    +deleteStaff(Staff Staff)
}

class StaffService {
    +FetchStaffbyID(long id): Staff
    +deleteStaff(Staff Staff)
}
class StaffRepository {
    +FetchStaffbyID(long id)
    +deleteStaff(Staff Staff)
}

Slots-->Staff : uses
ContactInformation-->Staff :has
Admin-|>User
Admin --> SessionManager : uses
IAMService --> SessionToken : returns
SessionManager --> Session : creates
Admin --> IAMService : authenticates with
Admin --> StaffController : inserts data into
StaffController-->StaffService: deletes  staff
Staff-->StaffController:uses
StaffService-->StaffRepository: deletes staff
SessionToken --> Session : verifies

@enduml