@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title 5.1.20 As an Admin, I want to add new types of operations, so that I can reflect the available medical procedures in the system.


autonumber
actor "Admin" as ADMIN

participant "<<System>> \nSystem" as System

    ADMIN -> System : selects to add a new operation 
    activate System

    System --> ADMIN : ask the information to create a new operation
    deactivate System

    ADMIN -> System : types the information
    activate System

    System --> ADMIN : message success
    deactivate System    

@enduml
