@startuml
'https://plantuml.com/class-diagram

skinparam monochrome true
skinparam shadowing false

title Class Diagram - As an Admin, I want to add new types of operations, so that I can reflect the available medical procedures in the system.

class Admin{

}
class Slots{
    +Date: Date
    +StartingHour: Date
    +EndHour: Date
}

class Staff{
    +FirstName: String
    +LastName: String
    +FullName: String
    +LicenseNumber(ID): long
    +ContactInformation(ID-FK):long
    +PhoneNumber: int
    +AvailabilitySlots: Slots

}

class ContactInformation{
    +ID:long
    +Email: String
    +PhoneNumber: int
}


class User{
    +ID: long
    +Username: String
    +Role: String
    +Email: String
}

class OperationType{
    +ID:long
    +Name:String
    +Staff: Staff
    +EstimatedDuration : Date

}



class SessionManager {
    +CreateSession(SessionToken token, Admin admin): Session
    +InvalidateSession(): void
}

class Session {
    +SessionID: string
    +Admin: Admin
    +CreatedAt: DateTime
    +ExpiresAt: DateTime
}
class IAMService {
    +Authenticate(IAMCredentials credentials): SessionToken
}



class SessionToken {
    +Token: string
    +Expiration: DateTime
    +IsValid(): bool
}

class OperationTypeController{
    +
}

class OperationTypeService {

}
class OperationTypeRepository {

}

Slots-->Staff : uses
ContactInformation-->Staff :has
Admin-|>User
Admin --> SessionManager : uses
IAMService --> SessionToken : returns
SessionManager --> Session : creates
Admin --> IAMService : authenticates with
Admin --> StaffController : inserts data into
StaffController-->StaffService: deletes  staff
Staff-->StaffController:uses
StaffService-->StaffRepository: deletes staff
SessionToken --> Session : verifies

@enduml