@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title 5.1.21 As an Admin, I want to edit existing operation types, so that I can update or correct information about the procedure.


autonumber
actor "Admin" as ADMIN

participant "<<System>> \nSystem" as System

    ADMIN -> System : selects to edit an operation 
    activate System

    System --> ADMIN : ask the information to edit an operation
    deactivate System

    ADMIN -> System : types the information
    activate System

    System --> ADMIN : message success
    deactivate System    

    
@enduml
