name: .NET CI

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'  # Run on every push to any branch
  pull_request:
    branches:
      - '**'  # Also run on pull requests to any branch

# The jobs that will run
jobs:
  build:

    # The type of machine the workflow will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks to be executed
    steps:
      # Checks out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Set up .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Specify your desired .NET version (e.g., 6.x or 7.x)

      # Install dependencies and restore any project-specific tools
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Run tests with code coverage
      - name: Run tests with coverage
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"